### ISSUE TITLE
04 - 02 - API Client

### ISSUE THREAD

**Issue by SShipton** [SShipton/assignments#13]
In this project, you will practice accessing an API. You'll see how an API request is made from code, and see how data is returned from an API.

## Objectives

- Demonstrate usage of APIs
- Understand how an API request is sent.
- Understand the request and response for an API.

### Explorer Mode

- [x] TOP TIP: Choose an API that has a simple, less nested API. Perhaps one that just returns an array of one-level-deep objects. This will make your task_significantly_ easier.
- [x] Choose one of the APIs from [this list](https://github.com/public-apis/public-apis) that does not request "AUTH" (Authorization) since an API that requires authorization is a little more difficult to use when first learning. I have also selected some sample APIs that will be good choices:

| API                                                      | Documentation                                  |
| -------------------------------------------------------- | ---------------------------------------------- |
| Dogs                                                     | https://dog.ceo/dog-api/                       |
| Studio Ghibli https://ghibliapi.herokuapp.com/#tag/Films |
| Open Brewery                                             | https://www.openbrewerydb.org/                 |
| Recipes                                                  | http://www.recipepuppy.com/about/api/          |
| Deck of Cards!                                           | http://deckofcardsapi.com/                     |
| Geocode                                                  | https://geocode.xyz/api                        |
| Jobs                                                     | https://jobs.github.com/api                    |
| Lyrics                                                   | https://lyricsovh.docs.apiary.io/#reference    |
| Quotes                                                   | https://pprathameshmore.github.io/QuoteGarden/ |
| SpaceX                                                   | https://docs.spacexdata.com/?version=latest    |
| Jokes                                                    | https://github.com/15Dkatz/official_joke_api   |

- [x] After choosing your API **read** the documentation.
- [x] Create a new `sdg-console` application for accessing the API.
- [x] Create a class to store information that comes back from your API.
- [x] Write code to query the API and show results.
- [ ] If your API has more than one endpoint (URL) support a few options,
      perhaps by creating a menu system in your application.

## Adventure Mode

Build a command line link shortening tool using this API: https://rel.ink/

Determine for yourself how you would like the tool to work, what the output
would look like, etc.

## Epic Mode

Use the site [Mockaroo](https://mockaroo.com/) to create a mock API. You may
need an account and then learn how their "Mock API" feature works.

Once you have created your Mock API for whatever schema you wish, implement a
client application to work with it.

**Comment by SShipton** [comment]
https://github.com/SShipton/APIClient/blob/master/Program.cs

I have my process for getting the two endpoints PEDAC'd, but I can't implement it since I can't test it (I got stuck on the *Unhandled exception.
System.Text.JsonException: '<' is an invalid start of a value.* error and have no clue why) and I'm not 100% confident in that, code as I am this. I coded alongside my rewatch of your lecture and the handbook side by side, but there was nothing in the handbook for menus, and I don't really have a place to implement it since I don't have my endpoints in.
Feeling really good about this code once I can get that error code sorted, I'll be working on it more tomorrow before lecture, and if I can't get it sorted then, I'll join lab time and ask for some help :^)
Today's lecture was actually really fun! It reminded me of the YouTube videos I keep running (in a good way!)

**Comment by gstark** [comment]
This is because you are confusing One List with your API.

You need to look at the pattern of the URL they document and use that. You are putting `/items?accessToken=...` where that is part of the *ONE LIST* api.

Your api uses URLs like `https://ghibliapi.herokuapp.com/films` -- try with that and you'll find more success. Each API has it's own URL structure you must follow.

**Comment by SShipton** [comment]
Your homework **04 - 02 - API Client** was marked: **Unacceptable**


![I'm just gonna...](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--354ad6ba2ab2a53888555f9ec77d2db94e87586c/nope.gif)
> &ldquo;I'm just gonna...&rdquo;

**Comment by SShipton** [comment]
https://github.com/SShipton/APIClient/blob/master/Program.cs

Progress! Started from scratch with a new API and had a much easier time. Almost done with this and then I'll be doing the C part of my PEDAC for the next assignment!

**Comment by SShipton** [comment]
Submitting for now, I'll come back to this later in the cohort if I end up needing the extra % in the end. Again, rewatching the lecture and coding alongside helped me tremendously- I wish I had thought of that in the beginning :) Will definitely be using this to my advantage in Unit 2 to hit 100%! Feeling confident that I can achieve that with my new strategy

**Comment by gstark** [comment]
Hi Skylar. I feel you are close but get tripped up on syntax and code formatting.

I sent you a "Pull Request" -- the idea of a Pull Request is me suggesting a code change to make your code work. You can read my changes and comments. It really was just a few small changes: https://github.com/SShipton/APIClient/pull/1

You can click on "Accept / Merge" the changes in and you will find your code runs fine!

**Comment by gstark** [comment]
I'm going to mark this homework as complete/acceptable.

**Comment by SShipton** [comment]
Your homework **04 - 02 - API Client** was marked: **Acceptable**


![Hmm ok ](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5311edd7d489ed156ec6b740b1cfac394c2c264/unicorn%20pug.gif)
> &ldquo;Hmm ok &rdquo;
