### ISSUE TITLE
04-03 - GET /practice?mode=api

### ISSUE THREAD

**Issue by SShipton** [SShipton/assignments#14]
## Objectives

- Create a simple API
- Practice problem solving

## Requirements

- Create 2 endpoints, `/mumbling` and `/explosion`, that are based off of the katas,`[https://www.codewars.com/kata/mumbling](https://www.codewars.com/kata/mumbling)` and `[https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion)` respectfully.

### Explorer Mode

- [x] Create a new `webapi` api project
- [ ] Create a endpoint for the `mumbling` endpoint
  - [x] Create a new Controller called `MumblingController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata [https://www.codewars.com/kata/mumbling(https://www.codewars.com/kata/mumbling) and return the result
  - [x] Have your code return the string
- [x] Create a endpoint for the `explosion` endpoint
  - [x] Create a new Controller called `ExplosionController`
  - [x] This will have one `HttpGet` method
  - [x] The method will accept a string either as a URL parameter or a query parameter. Your choice.
  - [x] This endpoint method will take the string passed to it, manipulate according to the kata
        [https://www.codewars.com/kata/digits-explosion(https://www.codewars.com/kata/digits-explosion) and return the result
  - [x] Have your code return the string

## Adventure Mode

None

## Epic Mode

None

## Resources

- Use [Insomnia](https://insomnia.rest/) for interacting with your API.

**Comment by SShipton** [comment]
I'm not sure why, but VS Code is absolutely refusing to push anything to github. I even tried editing my "queries.sql" file so that I could just push that, but that (in addition to the second attempt at making a PracticeModeAPI file) was futile. Instead, I've copy/pasted my two controllers here, and if I can't get this fixed tomorrow before lecture, I'm 100% going to pop in during lab time to get it sorted for the new unit. In the meantime, thank you for bearing with my temporary fix.

```
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;

namespace PracticeModeAPI.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MumblingController : ControllerBase
    {
        [HttpGet]
        public string ManipulateMumble(string mumbleInput)
        {
            var mumbleManipulator = mumbleInput.Select((character, index) => new String(character, index + 1)).Select(subString => subString.Substring(0, 1).ToUpper() + subString.Substring(1).ToLower());

            return string.Join("-", mumbleManipulator);
        }
    }
}


using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;

namespace PracticeModeAPI.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ExplosionController : ControllerBase
    {
        [HttpGet]
        public string ManipulateExplosion(string explosionInput)
        {
            var explosionManipulator = explosionInput.Select(character => new String(character, int.Parse(character.ToString())));

            return String.Concat(explosionManipulator);
        }
    }
}
```

-- My commit message was "Is it possible to put half of a bell here? :^)" --

**Comment by gstark** [comment]
This is great. I'll accept it from here!

**Comment by SShipton** [comment]
Your homework **04-03 - GET /practice?mode=api** was marked: **Meets Expectations**


![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5aaf4fb8aebc193771c4dd6c9823d8f6300ba70b/giphy-7.gif)
> &ldquo;Well done!&rdquo;
