### ISSUE TITLE
05 - 01 - Hello, HTML

### ISSUE THREAD

**Issue by SShipton** [SShipton/assignments#16]
In your first assignment, you will end up with a web page, no matter how simple,
published on the web.

You will create a simple website that will showcase one of your passions. This
is not about making the website flashy, but more about focusing on creating a
website and learning your new tools.

## Objectives

- Get to know your text editor
- Introduce yourself to working on the command line
- Write some HTML
- Publish a web page

## Requirements

- If you have experience with existing HTML/CSS frameworks (bootstrap, Bulma, etc) you may _not_ use them for these assignments.

### Explorer Mode

- [x] use `app-app HelloWorld` to create your first website.
- [x] Compose a short essay (just a couple paragraphs at most) about a hobby you either enjoy or would like to learn about. We might expand on this page in future assignments, so pick something fun!
- [x] Put your short essay into an HTML page, using appropriate semantic HTML elements. Give your webpage a simple header and footer as well.
- [x] Deploy your site.

**Comment by SShipton** [comment]
https://archery-skyla.netlify.app

yay! Quick question- in the step where it allowed us to pick our url, I changed "skyla" (what I have my name in my PC as) to "sshipton" (what I have as my github username) but it didn't actually change it. Is there an extra step I need to take to actually change that url, or should I just change my name in my PC to sshipton?

**Comment by gstark** [comment]
You can have it pickup your github name instead by using

```
git config --global github.user sshipton
```

And it should pick that up from now on.

**Comment by SShipton** [comment]
Your homework **05 - 01 - Hello, HTML** was marked: **Meets Expectations**


![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
