### ISSUE TITLE
05 - 03 - Flexbox flexing

### ISSUE THREAD

**Issue by SShipton** [SShipton/assignments#18]
Now that we have learned the power of flexbox we will apply it to the sites we
are building. We'll also go back to a past assignment and see how flexbox would
simplify our HTML and CSS.

## Objectives

- Build on your knowledge of HTML & CSS
- Use flexbox techniques layout pages.
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.

### Explorer Mode

- [x] Recommended: Go through the Flexbox Froggy and Grid Garden resources at the end of this homework.
- [ ] Recreate the page 'The Daily Kitteh' using flexbox and grids as closely as you possibly can. Use similar fonts, sizes, and colors. Feel free to use any cat photo you wish, just respect the relative size of the photo.
  - ![daily kitteh](https://raw.githubusercontent.com/suncoast-devs/handbook/a2f0c05d3914a8f16611da03a18dbe92cd821a92/curriculum/fundamentals/modules/html-css/lessons/css-layout/assignments/assets/daily-kitteh.png)

## Adventure Mode

- [ ] Recreate the page `Flexbox Article Layout` as closely as possible. Feel free to use flexbox, or grids, or both if needed. Here [a link to the HTML](https://gist.github.com/gstark/67f00631b3efe6145d34f9bfdf082637)
      ![flexbox article layout](https://raw.githubusercontent.com/suncoast-devs/handbook/a2f0c05d3914a8f16611da03a18dbe92cd821a92/curriculum/fundamentals/modules/html-css/lessons/css-layout/assignments/assets/flexbox-article-layout.png)

## Additional Resources

- CSS-Tricks guide to
  [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
- CSS-Tricks guide to
  [grids](https://css-tricks.com/snippets/css/complete-guide-grid/)
- http://www.evolutionoftheweb.com

## Recommended Practice:

- https://flexboxfroggy.com/
- https://http://cssgridgarden.com/
- https://mastery.games/p/flexbox-zombies

**Comment by SShipton** [comment]
https://github.com/SShipton/flexbox-flexing/tree/master/public

Basic styling done

Still need to add a few things, but leaving it here for now. Couldn't get deploy to work for this one for some reason, even though it's working with my others.

**Comment by SShipton** [comment]
Your homework **05 - 03 - Flexbox flexing** was marked: **Needs Improvement**


![Keep rolling with it](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBHZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a5861defaf25697d82b847afc71ef4a7637666f/chihuaha.gif)
> &ldquo;Keep rolling with it&rdquo;

**Comment by gstark** [comment]
This is a good start, but it doesn't yet really work with the Flexbox to place the cat sidebar next to the main article text. I'm going to send this back and see if you can finish that part.

The part in the red box here is important to implement.

![assignments 2020-06-30 14-07-12](https://user-images.githubusercontent.com/2607/86161277-02744580-badb-11ea-9e7b-b08886848d7a.png)

**Comment by SShipton** [comment]
https://github.com/SShipton/flexbox-flexing-2/blob/master/public/index.html

https://github.com/SShipton/flexbox-flexing-2/blob/master/public/screen.css

![image](https://user-images.githubusercontent.com/65146330/90086313-25079a00-dce8-11ea-89b9-a61db606105b.png)


woo!

**Comment by SShipton** [comment]
![image](https://user-images.githubusercontent.com/65146330/90086581-c131a100-dce8-11ea-89ed-bf9d16dca93d.png)

Changed some margins
