### ISSUE TITLE
02-03 Jurassic Park - 

### ISSUE THREAD

**Issue by SShipton** [SShipton/assignments#6]
In this assignment, you will be creating a console application that manages a zoo
full of dinosaurs.

## Objectives

- Practice control structures.
- Practice data structures.
- Practice working with user data.
- Practice with LINQ.
- Practice with OOP concepts.

## Requirements

- Create a console application that manages the dinosaurs in your zoo.

### Explorer Mode

- [x] Create a class to represent your dinosaurs. The class should have the following properties

  - [x] `Name`
  - [x] `DietType` - This will be "carnivore" or "herbivore"
  - [ ] `WhenAcquired` - This will default to the current time when the
        dinosaur is created
  - [x] `Weight` - How heavy the dinosaur is in pounds.
  - [x] `EnclosureNumber` - the number of the pen the dinosaur is currently in

- [x] Add a method `Description` to your class to print out a description of the dinosaur to include all of its properties. Create an output format of your choosing.
- [x] Your dinosaurs will be stored in a `List<Dinosaur>`.
- [x] When the console application runs, it should let the user choose one of the following actions:
  - [x] `View`
    - This command will show the all the dinosaurs in the list, ordered by `WhenAcquired`
  - [x] `Add`
    - This command will let the user type in the information for a dinosaur and add it to the list
  - [x] `Remove`
    - This command will prompt the user for a dinosaur name then find and delete the dinosaur with that name.
  - [x] `Transfer`
    - This command will prompt the user for a dinosaur name and a new `EnclosureNumber` and update that dino's information.
  - [ ] `Summary`
    - [ ] This command will display the number of carnivores and the number of herbivores.
  - [x] `Quit`
    - [x] This will stop the program

### Adventure Mode

- [ ] Add an option to view the Dinosaurs acquired after a given date (to be given by the user).
- [ ] Add an option to view all the Dinosaurs in a given enclosure number.

### Epic Mode

- [ ] Learn how to read and write from a file. At the start of the program load all the dinosaurs from a file. When the program ends write out all the dinosaurs to the same file.

**Comment by SShipton** [comment]
https://github.com/SShipton/JurassicPark

Tomorrow I need to fix:
Parsing for my enclosure number and weight
Log error ?
Carnivore/Herbivore categorization
DateTime (simplest one to add. future self, start here)

Happy with everything else so far! In the evening, after I've been coding for a few hours already, I'll rewatch the lecture/with me at 3 and "code along", and I used some of the things from my temp file that I used to code along with in this project. Rewatching the lecture and coding along with you while you explain the purpose helps me link the code and the reasoning!

**Comment by gstark** [comment]
Nicely done. I'm going to reopen this to remind you to finish those items. But a very good job so far!

**Comment by SShipton** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Unacceptable**

![:/](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd007c020ded3e37161fc5e46b000f3f904807e7/david.gif)
> &ldquo;:/&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/4)**__

**Comment by SShipton** [comment]
https://github.com/SShipton/JurassicPark

Attempted a few fixes, while not everything I did worked, rewatching the lecture helped a TON and I'm feeling far more confident going into Unit 2 with the knowledge that I have.

**Comment by gstark** [comment]
Reading the code tells me you are getting the ideas but need some focus on ensuring you understand the syntax.

Even though the code does not run I am going to accept this assignment. When we return to C# after our front end work you'll have more chances to practice.

**Comment by SShipton** [comment]
Your homework **02-03 Jurassic Park - ** was marked: **Acceptable**


![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
